In [83]:
#Method 1 of how to build a dataset, using tf.data.dataset

In [69]:
import tensorflow as tf
import numpy as np

In [51]:
#Setting up filenames (X)

filenames = []

for i in range(10):
    name = f"A{i+1}.png"
    filenames.append(name)
    
for i in range(10):
    name = f"B{i+1}.png"
    filenames.append(name)

In [70]:
#Setting up labels (Y)

labels = []

for i in filenames:
    if "A" in i:
        labels.append(0)
    elif "B" in i:
        labels.append(1)
    
labels = np.array(labels, dtype=np.uint8)


In [71]:
#create data structure

dataset = tf.data.Dataset.from_tensor_slices((filenames, labels))

In [72]:
#function o assign the images and labels

def _parse_function(filename, label):
    image_string = tf.io.read_file(f"../datasets/teste1/{filename}")
    image_decoded = tf.image.decode_png(image_string, channels=3)
    image = tf.cast(image_decoded, tf.float32)
    return image, label

In [73]:
#mount dataset

dataset = dataset.map(im_file_to_tensor)
dataset = dataset.batch(2)

In [74]:
#thats it!

for next_element in dataset:
    tf.print(next_element)

([[[[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  ...

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  ...

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]]], [0 0])
([[[[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

([[[[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  ...

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  ...

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   ...
   [1 1 1]
   [1 1 1]
   [1 1 1]]]], [1 1])
